services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: base
    env_file:
      - .env.local
    volumes:
      - $PWD/app:/app/app
      - $PWD/public:/app/public
      - $PWD/middleware.ts:/app/middleware.ts
      - $PWD/instrumentation.ts:/app/instrumentation.ts
      - $PWD/game.json:/app/game.json
    ports:
      - 3000:3000
    command: ["pnpm", "dev"]
  redis:
    image: redis:6.2.20
    volumes:
      - $PWD/redis:/data
    ports:
      - 6379:6379
  mongo:
    image: mongo:8.2.1
    volumes:
      - $PWD/mongo:/data/db
    ports:
      - 27017:27017
